To test serialization issue
Getting an issue trying to load "AttributeError: 'Player' object has no attribute '_id'"
Making this change to see if the leading _ is the problem